<?
$PERM["seminary"]["2"]="R";
$PERM["seminary"]["3"]="R";
$PERM["seminary"]["4"]="R";
$PERM["seminary"]["5"]="R";
$PERM["seminary"]["*"]="R";
$PERM["search"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["about"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>